// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/pkg/models/shared"
	"net/http"
)

type BatchRequest struct {
	RequestBody []string `request:"mediaType=application/json"`
	VehicleID   string   `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type BatchResponse struct {
	// A list of responses from multiple Smartcar endpoints
	BatchResponse *shared.BatchResponse
	ContentType   string
	StatusCode    int
	RawResponse   *http.Response
}
