// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/pkg/models/shared"
	"net/http"
)

type BatchRequest struct {
	RequestBody []string `request:"mediaType=application/json"`
	VehicleID   string   `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

func (o *BatchRequest) GetRequestBody() []string {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *BatchRequest) GetVehicleID() string {
	if o == nil {
		return ""
	}
	return o.VehicleID
}

type BatchResponse struct {
	// A list of responses from multiple Smartcar endpoints
	BatchResponse *shared.BatchResponse
	ContentType   string
	StatusCode    int
	RawResponse   *http.Response
}

func (o *BatchResponse) GetBatchResponse() *shared.BatchResponse {
	if o == nil {
		return nil
	}
	return o.BatchResponse
}

func (o *BatchResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *BatchResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *BatchResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
