// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/pkg/models/shared"
	"net/http"
)

type GetBatteryCapacityRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type GetBatteryCapacityResponse struct {
	// return EV Battery Capacity reading
	BatteryCapacity *shared.BatteryCapacity
	ContentType     string
	StatusCode      int
	RawResponse     *http.Response
}
