// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"smartcar/pkg/models/shared"
)

type GetChargingLimitRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type GetChargingLimitResponse struct {
	// return EV Charge Limit
	ChargeLimit *shared.ChargeLimit
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
