// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"smartcar/pkg/models/shared"
)

type GetChevroletChargeTimeRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type GetChevroletChargeTimeResponse struct {
	// returns the date and time the vehicle expects to "complete" this charging session.
	ChargeTime  *shared.ChargeTime
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
