// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/pkg/models/shared"
	"net/http"
)

type GetFuelTankRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type GetFuelTankResponse struct {
	ContentType string
	// return fuel tank reading
	FuelTank    *shared.FuelTank
	StatusCode  int
	RawResponse *http.Response
}
