// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/pkg/models/shared"
	"net/http"
)

type GetOdometerRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

func (o *GetOdometerRequest) GetVehicleID() string {
	if o == nil {
		return ""
	}
	return o.VehicleID
}

type GetOdometerResponse struct {
	ContentType string
	// return odometer reading
	Odometer    *shared.Odometer
	StatusCode  int
	RawResponse *http.Response
}

func (o *GetOdometerResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetOdometerResponse) GetOdometer() *shared.Odometer {
	if o == nil {
		return nil
	}
	return o.Odometer
}

func (o *GetOdometerResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetOdometerResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
