// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Smartcar-API/pkg/models/shared"
	"net/http"
)

type GetTeslaCompassRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type GetTeslaCompassResponse struct {
	// returns the compass heading of a Tesla.
	Compass     *shared.Compass
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
