// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Smartcar-API/pkg/models/shared"
	"net/http"
)

type GetTeslaInteriorTemperatureRequest struct {
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type GetTeslaInteriorTemperatureResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// returns the interior temperature of a Tesla.
	Temperature *shared.Temperature
}
