// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/pkg/models/shared"
	"net/http"
)

type GetVinRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type GetVinResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// return EV Battery Capacity reading
	VinInfo *shared.VinInfo
}
