// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"smartcar/pkg/models/shared"
)

type GetVehicleRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type GetVehicleResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A single vehicles
	VehicleInfo *shared.VehicleInfo
}
