// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"smartcar/pkg/models/shared"
)

type ListVehiclesRequest struct {
	// Number of vehicles to return
	Limit *int64 `queryParam:"style=form,explode=true,name=limit"`
	// Index to start vehicle list at
	Offset *int64 `queryParam:"style=form,explode=true,name=offset"`
}

type ListVehiclesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// A list of vehicles
	VehiclesResponse *shared.VehiclesResponse
}
