// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"smartcar/pkg/models/shared"
)

type ListCompatibilityRequest struct {
	Country *string `queryParam:"style=form,explode=true,name=country"`
	Scope   *string `queryParam:"style=form,explode=true,name=scope"`
	Vin     *string `queryParam:"style=form,explode=true,name=vin"`
}

type ListCompatibilityResponse struct {
	// return Compatibility
	CompatibilityResponse *shared.CompatibilityResponse
	ContentType           string
	StatusCode            int
	RawResponse           *http.Response
}
