// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/v3/pkg/models/shared"
	"net/http"
)

type LockUnlockRequest struct {
	SecurityAction *shared.SecurityAction `request:"mediaType=application/json"`
	VehicleID      string                 `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

func (o *LockUnlockRequest) GetSecurityAction() *shared.SecurityAction {
	if o == nil {
		return nil
	}
	return o.SecurityAction
}

func (o *LockUnlockRequest) GetVehicleID() string {
	if o == nil {
		return ""
	}
	return o.VehicleID
}

type LockUnlockResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// return Compatibility
	SuccessResponse *shared.SuccessResponse
}

func (o *LockUnlockResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LockUnlockResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LockUnlockResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *LockUnlockResponse) GetSuccessResponse() *shared.SuccessResponse {
	if o == nil {
		return nil
	}
	return o.SuccessResponse
}
