// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/smartcar/go-sdk-v2/v2/pkg/models/shared"
	"net/http"
)

type LockStatusRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

func (o *LockStatusRequest) GetVehicleID() string {
	if o == nil {
		return ""
	}
	return o.VehicleID
}

type LockStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Returns the lock status for a vehicle and the open status of its doors, windows, storage units, sunroof and charging port where available.
	SecurityRead *shared.SecurityRead
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *LockStatusResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *LockStatusResponse) GetSecurityRead() *shared.SecurityRead {
	if o == nil {
		return nil
	}
	return o.SecurityRead
}

func (o *LockStatusResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *LockStatusResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
