// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Smartcar-API/pkg/models/shared"
	"net/http"
)

type StartStopChargeRequest struct {
	ChargeAction *shared.ChargeAction `request:"mediaType=application/json"`
	VehicleID    string               `pathParam:"style=simple,explode=false,name=vehicle_id"`
}

type StartStopChargeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// return Success Response
	SuccessResponse *shared.SuccessResponse
}
