// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"Smartcar-API/pkg/models/shared"
	"net/http"
)

type UnsubscribeRequest struct {
	VehicleID string `pathParam:"style=simple,explode=false,name=vehicle_id"`
	WebhookID string `pathParam:"style=simple,explode=false,name=webhookId"`
}

type UnsubscribeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Ubsubscribe from a webhook
	SuccessResponse *shared.SuccessResponse
}
