// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BatchRequest struct {
	Requests []Path `json:"requests,omitempty"`
}

func (o *BatchRequest) GetRequests() []Path {
	if o == nil {
		return nil
	}
	return o.Requests
}
