// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// BatchResponse - A list of responses from multiple Smartcar endpoints
type BatchResponse struct {
	Responses []Response `json:"responses,omitempty"`
}
