// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BatteryLevel struct {
	// An EV battery’s state of charge (in percent).
	PercentRemaining float32 `json:"percentRemaining"`
	// The estimated remaining distance the vehicle can travel (in kilometers by default or in miles using the sc-unit-system).
	Range float32 `json:"range"`
}

func (o *BatteryLevel) GetPercentRemaining() float32 {
	if o == nil {
		return 0.0
	}
	return o.PercentRemaining
}

func (o *BatteryLevel) GetRange() float32 {
	if o == nil {
		return 0.0
	}
	return o.Range
}
