// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type BatteryLevel struct {
	// An EV battery’s state of charge (in percent).
	PercentRemaining *float32 `json:"percentRemaining,omitempty"`
	// The estimated remaining distance the vehicle can travel (in kilometers by default or in miles using the sc-unit-system).
	Range *float32 `json:"range,omitempty"`
}
