// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Capability struct {
	Capable    *bool   `json:"capable,omitempty"`
	Endpoint   *string `json:"endpoint,omitempty"`
	Permission *string `json:"permission,omitempty"`
	Reason     *string `json:"reason,omitempty"`
}
