// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ChargeAmmeter struct {
	// The amperage of the charger measured by the vehicle.
	Amperage *float32 `json:"amperage,omitempty"`
}

func (o *ChargeAmmeter) GetAmperage() *float32 {
	if o == nil {
		return nil
	}
	return o.Amperage
}
