// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ChargeLimit struct {
	// The level at which the vehicle should stop charging and be considered fully charged (in percent).
	Limit *float32 `json:"limit,omitempty"`
}
