// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ChargeLimit struct {
	// The level at which the vehicle should stop charging and be considered fully charged (in percent).
	Limit float32 `json:"limit"`
}

func (o *ChargeLimit) GetLimit() float32 {
	if o == nil {
		return 0.0
	}
	return o.Limit
}
