// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ChargeTime struct {
	// The date and time the vehicle expects to complete this charging session.
	Time *time.Time `json:"time,omitempty"`
}
