// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ChargeAmmeter - returns the amperage of the charger measured by the vehicle.
type ChargeAmmeter struct {
	// The amperage of the charger measured by the vehicle.
	Amperage *float32 `json:"amperage,omitempty"`
}
