// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ChargeVoltage struct {
	// The voltage of the charger measured by the vehicle.
	Voltage float32 `json:"voltage"`
}

func (o *ChargeVoltage) GetVoltage() float32 {
	if o == nil {
		return 0.0
	}
	return o.Voltage
}
