// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/smartcar/go-sdk-v2/pkg/utils"
	"time"
)

type ChargeTime struct {
	// The date and time the vehicle expects to complete this charging session.
	Time time.Time `json:"time"`
}

func (c ChargeTime) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChargeTime) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ChargeTime) GetTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.Time
}
