// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CompatibilityResponse struct {
	Capabilities []Capability `json:"capabilities"`
	Compatible   bool         `json:"compatible"`
	Reason       *string      `json:"reason"`
}

func (o *CompatibilityResponse) GetCapabilities() []Capability {
	if o == nil {
		return []Capability{}
	}
	return o.Capabilities
}

func (o *CompatibilityResponse) GetCompatible() bool {
	if o == nil {
		return false
	}
	return o.Compatible
}

func (o *CompatibilityResponse) GetReason() *string {
	if o == nil {
		return nil
	}
	return o.Reason
}
