// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// CompatibilityResponse - return Compatibility
type CompatibilityResponse struct {
	Capabilities []Capability `json:"capabilities,omitempty"`
	Compatible   *bool        `json:"compatible,omitempty"`
	Reason       *string      `json:"reason,omitempty"`
}
