// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CursorPaging struct {
	Cursor *string `json:"cursor,omitempty"`
}

func (o *CursorPaging) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}
