// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DeletedConnection struct {
	UserID    *string `json:"userId,omitempty"`
	VehicleID *string `json:"vehicleId,omitempty"`
}

func (o *DeletedConnection) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *DeletedConnection) GetVehicleID() *string {
	if o == nil {
		return nil
	}
	return o.VehicleID
}
