// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EngineOil struct {
	// The engine oil’s remaining life span (as a percentage). Oil life is based on the current quality of the oil. (in percent).
	LifeRemaining float32 `json:"lifeRemaining"`
}

func (o *EngineOil) GetLifeRemaining() float32 {
	if o == nil {
		return 0.0
	}
	return o.LifeRemaining
}
