// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type FuelTank struct {
	// The amount of fuel in the tank (in liters by default or in gallons (U.S.) using the sc-unit-system).
	AmountRemaining float32 `json:"amountRemaining"`
	// The remaining level of fuel in the tank (in percent).
	PercentRemaining float32 `json:"percentRemaining"`
	// The estimated remaining distance the car can travel (in kilometers by default or in miles using the sc-unit-system).
	Range float32 `json:"range"`
}

func (o *FuelTank) GetAmountRemaining() float32 {
	if o == nil {
		return 0.0
	}
	return o.AmountRemaining
}

func (o *FuelTank) GetPercentRemaining() float32 {
	if o == nil {
		return 0.0
	}
	return o.PercentRemaining
}

func (o *FuelTank) GetRange() float32 {
	if o == nil {
		return 0.0
	}
	return o.Range
}
