// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FuelTank - return fuel tank reading
type FuelTank struct {
	// The amount of fuel in the tank (in liters by default or in gallons (U.S.) using the sc-unit-system).
	AmountRemaining *float32 `json:"amountRemaining,omitempty"`
	// The remaining level of fuel in the tank (in percent).
	PercentRemaining *float32 `json:"percentRemaining,omitempty"`
	// The estimated remaining distance the car can travel (in kilometers by default or in miles using the sc-unit-system).
	Range *float32 `json:"range,omitempty"`
}
