// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"github.com/smartcar/go-sdk-v2/v2/pkg/utils"
	"time"
)

type GetConnection struct {
	ConnectedAt *time.Time `json:"connectedAt,omitempty"`
	UserID      *string    `json:"userId,omitempty"`
	VehicleID   *string    `json:"vehicleId,omitempty"`
}

func (g GetConnection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetConnection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetConnection) GetConnectedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.ConnectedAt
}

func (o *GetConnection) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}

func (o *GetConnection) GetVehicleID() *string {
	if o == nil {
		return nil
	}
	return o.VehicleID
}
