// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Header struct {
	ScDataAge    *string `json:"sc-data-age,omitempty"`
	ScUnitSystem *string `json:"sc-unit-system,omitempty"`
}

func (o *Header) GetScDataAge() *string {
	if o == nil {
		return nil
	}
	return o.ScDataAge
}

func (o *Header) GetScUnitSystem() *string {
	if o == nil {
		return nil
	}
	return o.ScUnitSystem
}
