// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Header struct {
	ScDataAge    *string `json:"sc-data-age,omitempty"`
	ScUnitSystem *string `json:"sc-unit-system,omitempty"`
}
