// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Location - A list of vehicles
type Location struct {
	Latitude  float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
}
