// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Odometer struct {
	Distance float32 `json:"distance"`
}

func (o *Odometer) GetDistance() float32 {
	if o == nil {
		return 0.0
	}
	return o.Distance
}
