// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Odometer struct {
	Distance *float32 `json:"distance,omitempty"`
}

func (o *Odometer) GetDistance() *float32 {
	if o == nil {
		return nil
	}
	return o.Distance
}
