// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PermissionPaging struct {
	Count  *int64 `json:"count,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// Permission - The applications permissions
type Permission struct {
	Paging      *PermissionPaging `json:"paging,omitempty"`
	Permissions []string          `json:"permissions,omitempty"`
}
