// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Paging struct {
	Count  *int64 `json:"count,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

func (o *Paging) GetCount() *int64 {
	if o == nil {
		return nil
	}
	return o.Count
}

func (o *Paging) GetOffset() *int64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

type Permission struct {
	Paging      *Paging  `json:"paging,omitempty"`
	Permissions []string `json:"permissions,omitempty"`
}

func (o *Permission) GetPaging() *Paging {
	if o == nil {
		return nil
	}
	return o.Paging
}

func (o *Permission) GetPermissions() []string {
	if o == nil {
		return nil
	}
	return o.Permissions
}
