// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SendDestination struct {
	Latitude  float32 `json:"latitude"`
	Longitude float32 `json:"longitude"`
}

func (o *SendDestination) GetLatitude() float32 {
	if o == nil {
		return 0.0
	}
	return o.Latitude
}

func (o *SendDestination) GetLongitude() float32 {
	if o == nil {
		return 0.0
	}
	return o.Longitude
}
