// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Status string

const (
	StatusSuccess Status = "success"
	StatusFailed  Status = "failed"
)

func (e Status) ToPointer() *Status {
	return &e
}
func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "failed":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type SuccessResponse struct {
	Message *string `json:"message,omitempty"`
	Status  Status  `json:"status"`
}

func (o *SuccessResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *SuccessResponse) GetStatus() Status {
	if o == nil {
		return Status("")
	}
	return o.Status
}
