// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Temperature - returns the exterior temperature of a Tesla.
type Temperature struct {
	Temperature *float32 `json:"temperature,omitempty"`
}
