// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TirePressure struct {
	// The current air pressure of the back left tire (in kilopascals by default or in pounds per square inch using the sc-unit-system).
	BackLeft float32 `json:"backLeft"`
	// The current air pressure of the back right tire (in kilopascals by default or in pounds per square inch using the sc-unit-system).
	BackRight float32 `json:"backRight"`
	// The current air pressure of the front left tire (in kilopascals by default or in pounds per square inch using the sc-unit-system).
	FrontLeft float32 `json:"frontLeft"`
	// The current air pressure of the front right tire (in kilopascals by default or in pounds per square inch using the sc-unit-system).
	FrontRight float32 `json:"frontRight"`
}

func (o *TirePressure) GetBackLeft() float32 {
	if o == nil {
		return 0.0
	}
	return o.BackLeft
}

func (o *TirePressure) GetBackRight() float32 {
	if o == nil {
		return 0.0
	}
	return o.BackRight
}

func (o *TirePressure) GetFrontLeft() float32 {
	if o == nil {
		return 0.0
	}
	return o.FrontLeft
}

func (o *TirePressure) GetFrontRight() float32 {
	if o == nil {
		return 0.0
	}
	return o.FrontRight
}
