// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// UserInfo - A user ID (UUID v4).
type UserInfo struct {
	ID string `json:"id"`
}

func (o *UserInfo) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}
