// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// VehicleInfo - A single vehicles
type VehicleInfo struct {
	ID    string `json:"id"`
	Make  string `json:"make"`
	Model string `json:"model"`
	Year  int64  `json:"year"`
}
