// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type VehiclesResponsePaging struct {
	Count  *int64 `json:"count,omitempty"`
	Offset *int64 `json:"offset,omitempty"`
}

// VehiclesResponse - A list of vehicles
type VehiclesResponse struct {
	Paging   *VehiclesResponsePaging `json:"paging,omitempty"`
	Vehicles []string                `json:"vehicles,omitempty"`
}
