// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// VinInfo - A vehicle’s manufacturer identifier.
type VinInfo struct {
	Vin *string `json:"vin,omitempty"`
}

func (o *VinInfo) GetVin() *string {
	if o == nil {
		return nil
	}
	return o.Vin
}
